name: Global workflow to rule them all

on:
  push:
    branches: [ main ] #or main
  workflow_dispatch: {} #to enable manual triggering of the action

jobs:

  replicate_changes:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Replicating global workflow
          uses: derberg/manage-files-in-multiple-repositories@v2
          with:
            github_token: ${{ secrets.MANAGE_FILES_TOKEN }}
            patterns_to_ignore: '.github/workflows/greetings.yml'
            patterns_to_include: '.github/workflows'
            #repos_to_ignore: '*'
            repos_to_ignore: gitpractice,bashscripts,ansiblescripts,sonarqube-wiki,skills-hello-github-actions,Project_1,template-with-workflows,template-from-bashscripts,bashscripts-template,Final_Project,codespaces-jupyter,
            exclude_private: true
            exclude_forked: true
            branches: main
            #destination: 'gitpractice'
            committer_username: prithvikumar.detne@gmail.com
            committer_email: prithvikumar.detne@gmail.com
            commit_message: "Commit Message 1 "

name: Global workflow to rule them all

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      repo_name:
        description: |
          manage-files-1
        required: false

jobs:

  replicate_coc:
      name: Replicate Code of Conduct in all repositories
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Replicating file
        uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: ${{ secrets.MANAGE_FILES_TOKEN }}
          patterns_to_include: .github/workflows
          committer_username: prithvikumar.detne@gmail.com
          committer_email: prithvikumar.detne@gmail.com
          commit_message: "Single Repository commit"
          #repos_to_ignore: shape-up-process,glee-hello-world
          exclude_private: true
          exclude_forked: true
          branches: main
